import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatCurrency, formatDate } from './format'

const SLATE = [71, 85, 105]
const LIGHT = [240, 253, 244] // primary-50 tint

function hexToRgb(hex) {
  if (!hex) return [21, 128, 61]
  const clean = hex.replace('#', '')
  const bigint = parseInt(clean, 16)
  if (Number.isNaN(bigint)) return [21, 128, 61]
  return [(bigint >> 16) & 255, (bigint >> 8) & 255, bigint & 255]
}

/**
 * Fetches a remote image URL and converts it to a data URL. jsPDF's
 * addImage() does not reliably accept a bare remote URL in the browser -
 * this was why an uploaded logo/signature never actually showed up in
 * generated PDFs even though the upload itself worked fine. Returns null on
 * any failure so callers can fall back gracefully instead of breaking PDF
 * generation entirely.
 */
async function urlToDataUrl(url) {
  if (!url) return null
  try {
    const res = await fetch(url)
    if (!res.ok) return null
    const blob = await res.blob()
    return await new Promise((resolve) => {
      const reader = new FileReader()
      reader.onload = () => resolve(reader.result)
      reader.onerror = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch (e) {
    return null
  }
}

function imageFormatFromDataUrl(dataUrl) {
  if (dataUrl?.startsWith('data:image/png')) return 'PNG'
  if (dataUrl?.startsWith('data:image/webp')) return 'WEBP'
  return 'JPEG'
}

function baseDoc(settings) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const primary = hexToRgb(settings.primary_color)
  return { doc, primary }
}

async function drawHeader(doc, primary, settings, docTitleRight) {
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 40

  doc.setFillColor(...primary)
  doc.rect(0, 0, pageWidth, 90, 'F')

  const logoDataUrl = await urlToDataUrl(settings.logo_url)
  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, imageFormatFromDataUrl(logoDataUrl), margin, 25, 40, 40)
    } catch (e) {
      drawInitialsBadge(doc, primary, settings, margin)
    }
  } else {
    drawInitialsBadge(doc, primary, settings, margin)
  }

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(settings.company_name || 'CHIMACY OF UNN', margin + 55, 38)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(settings.tagline || 'Admission Consulting Services', margin + 55, 53)
  doc.text(`${settings.phone || ''}   |   ${settings.email || ''}`, margin + 55, 66)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(docTitleRight.label, pageWidth - margin, 38, { align: 'right' })
  doc.setFont('helvetica', 'normal')
  doc.text(docTitleRight.value, pageWidth - margin, 53, { align: 'right' })

  return margin
}

function drawInitialsBadge(doc, primary, settings, margin) {
  doc.setFillColor(255, 255, 255)
  doc.circle(margin + 20, 45, 20, 'F')
  doc.setTextColor(...primary)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(initials(settings.company_name), margin + 20, 50, { align: 'center' })
}

function sectionHeader(doc, primary, title, margin, y) {
  doc.setFillColor(...primary)
  doc.rect(margin, y - 12, 4, 16, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(30, 41, 59)
  doc.text(title, margin + 12, y)
  return y + 20
}

function initials(name) {
  if (!name) return 'CU'
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0].toUpperCase())
    .join('')
}

function footerEveryPage(doc, settings) {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 40
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i)
    doc.setDrawColor(220, 240, 227)
    doc.line(margin, pageHeight - 55, pageWidth - margin, pageHeight - 55)
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.setFont('helvetica', 'normal')
    doc.text(settings.footer_text || `Generated by ${settings.company_name}`, margin, pageHeight - 38)
    doc.text(settings.address || settings.institution_name || '', margin, pageHeight - 26)
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 38, { align: 'right' })
    doc.text(`Generated: ${formatDate(new Date())}`, pageWidth - margin, pageHeight - 26, { align: 'right' })
  }
}

/**
 * Generates a professional, multi-page PDF quotation and returns the jsPDF
 * document instance (caller decides to save/preview). Async because the
 * logo/signature images are fetched and embedded properly.
 */
export async function generateQuotationPDF(quotation, settings) {
  const { doc, primary } = baseDoc(settings)
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const currencySymbol = settings.currency_symbol || '\u20a6'
  let y

  const margin = await drawHeader(doc, primary, settings, { label: `Quotation No: ${quotation.quotationNumber}`, value: `Date: ${formatDate(quotation.date)}` })
  y = 120

  doc.setTextColor(30, 41, 59)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('ADMISSION QUOTATION REPORT', pageWidth / 2, y, { align: 'center' })
  y += 10
  doc.setDrawColor(...primary)
  doc.setLineWidth(1.2)
  doc.line(pageWidth / 2 - 90, y, pageWidth / 2 + 90, y)
  y += 30

  y = sectionHeader(doc, primary, 'Client Details', margin, y)
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 4, textColor: [30, 41, 59] },
    body: [
      ['Client Name', quotation.clientName || '-', 'Phone Number', quotation.phone || '-'],
      ['Parent Name', quotation.parentName || '-', 'Email', quotation.email || '-'],
      ['JAMB Reg. Number', quotation.jambRegNumber || '-', 'JAMB Score', String(quotation.jambScore ?? '-')],
      ['Institution', settings.institution_name || 'University of Nigeria, Nsukka', 'Category', quotation.category || '-'],
    ],
    columnStyles: {
      0: { fontStyle: 'bold', textColor: SLATE, cellWidth: 120 },
      1: { cellWidth: 130 },
      2: { fontStyle: 'bold', textColor: SLATE, cellWidth: 120 },
      3: { cellWidth: 'auto' },
    },
    didParseCell: (data) => { if (data.row.index % 2 === 0) data.cell.styles.fillColor = LIGHT },
  })
  y = doc.lastAutoTable.finalY + 25

  y = sectionHeader(doc, primary, 'Programme & Pricing', margin, y)
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Programme', 'Grade', 'Working Type', 'Price']],
    body: [[quotation.programme || '-', quotation.programmeGrade || '-', quotation.workingType || '-', formatCurrency(quotation.price, currencySymbol)]],
    theme: 'grid',
    headStyles: { fillColor: primary, textColor: 255, fontStyle: 'bold', fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 6, textColor: [30, 41, 59] },
  })
  y = doc.lastAutoTable.finalY + 25

  y = sectionHeader(doc, primary, 'Benchmark Analysis & Eligibility', margin, y)
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 4, textColor: [30, 41, 59] },
    body: [
      ['Eligibility Status', quotation.status || '-'],
      ['Benchmark Status', quotation.benchmarkStatus || '-'],
      ['Recommendation', quotation.recommendation || '-'],
    ],
    columnStyles: { 0: { fontStyle: 'bold', textColor: SLATE, cellWidth: 140 }, 1: { cellWidth: 'auto' } },
    didParseCell: (data) => { if (data.row.index % 2 === 0) data.cell.styles.fillColor = LIGHT },
  })
  y = doc.lastAutoTable.finalY + 20

  if (quotation.remarks) {
    y = sectionHeader(doc, primary, 'Remarks', margin, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(51, 65, 85)
    const remarksLines = doc.splitTextToSize(quotation.remarks, pageWidth - margin * 2)
    doc.text(remarksLines, margin, y)
    y += remarksLines.length * 14 + 15
  }

  doc.addPage()
  y = margin
  y = sectionHeader(doc, primary, 'Terms & Conditions', margin, y)
  const rules = quotation.rulesSnapshot?.length ? quotation.rulesSnapshot : []
  doc.setFontSize(10)
  rules.forEach((rule, idx) => {
    const bodyLines = doc.splitTextToSize(`${rule.title ? rule.title + ' - ' : ''}${rule.text}`, pageWidth - margin * 2 - 18)
    if (y + bodyLines.length * 14 > pageHeight - 140) { doc.addPage(); y = margin }
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...primary)
    doc.text(`${idx + 1}.`, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(51, 65, 85)
    doc.text(bodyLines, margin + 18, y)
    y += bodyLines.length * 14 + 10
  })
  y += 15

  if (y > pageHeight - 160) { doc.addPage(); y = margin }
  y = sectionHeader(doc, primary, 'Acknowledgement', margin, y)
  doc.setFontSize(9.5)
  doc.setTextColor(51, 65, 85)
  doc.setFont('helvetica', 'normal')
  doc.text(
    'By signing below, the client acknowledges having read, understood, and agreed to the terms and conditions stated in this quotation.',
    margin, y, { maxWidth: pageWidth - margin * 2 },
  )
  y += 50
  await drawSignatureBlock(doc, settings, margin, pageWidth, y)

  footerEveryPage(doc, settings)
  return doc
}

/**
 * Generates a professional invoice/receipt PDF for a paid client.
 */
export async function generateInvoicePDF(quotation, settings) {
  const { doc, primary } = baseDoc(settings)
  const pageWidth = doc.internal.pageSize.getWidth()
  const currencySymbol = settings.currency_symbol || '\u20a6'
  let y

  const margin = await drawHeader(doc, primary, settings, { label: `Invoice No: ${quotation.invoiceNumber || '-'}`, value: `Date: ${formatDate(quotation.paidDate)}` })
  y = 120

  doc.setTextColor(30, 41, 59)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('PAYMENT INVOICE / RECEIPT', pageWidth / 2, y, { align: 'center' })
  y += 10
  doc.setDrawColor(...primary)
  doc.setLineWidth(1.2)
  doc.line(pageWidth / 2 - 90, y, pageWidth / 2 + 90, y)
  y += 30

  y = sectionHeader(doc, primary, 'Billed To', margin, y)
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 4, textColor: [30, 41, 59] },
    body: [
      ['Client Name', quotation.clientName || '-', 'Phone Number', quotation.phone || '-'],
      ['Quotation No.', quotation.quotationNumber || '-', 'Institution', settings.institution_name || 'University of Nigeria, Nsukka'],
    ],
    columnStyles: {
      0: { fontStyle: 'bold', textColor: SLATE, cellWidth: 120 },
      1: { cellWidth: 130 },
      2: { fontStyle: 'bold', textColor: SLATE, cellWidth: 120 },
      3: { cellWidth: 'auto' },
    },
    didParseCell: (data) => { if (data.row.index % 2 === 0) data.cell.styles.fillColor = LIGHT },
  })
  y = doc.lastAutoTable.finalY + 25

  y = sectionHeader(doc, primary, 'Payment Details', margin, y)
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Description', 'Working Type', 'Payment Method', 'Amount Paid']],
    body: [[
      quotation.programme || '-',
      quotation.workingType || '-',
      quotation.paymentMethod || '-',
      formatCurrency(quotation.paidAmount || quotation.price, currencySymbol),
    ]],
    theme: 'grid',
    headStyles: { fillColor: primary, textColor: 255, fontStyle: 'bold', fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 6, textColor: [30, 41, 59] },
  })
  y = doc.lastAutoTable.finalY + 15

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(...primary)
  doc.text(`Total Paid: ${formatCurrency(quotation.paidAmount || quotation.price, currencySymbol)}`, pageWidth - margin, y, { align: 'right' })
  y += 20

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9.5)
  doc.setTextColor(51, 65, 85)
  doc.text('This invoice confirms receipt of payment. Refunds are subject to the Rules & Guidelines on file.', margin, y, { maxWidth: pageWidth - margin * 2 })
  y += 40

  await drawSignatureBlock(doc, settings, margin, pageWidth, y)
  footerEveryPage(doc, settings)
  return doc
}

async function drawSignatureBlock(doc, settings, margin, pageWidth, y) {
  const colWidth = (pageWidth - margin * 2 - 40) / 2
  doc.setDrawColor(148, 163, 184)
  doc.line(margin, y, margin + colWidth, y)
  doc.line(margin + colWidth + 40, y, margin + colWidth * 2 + 40, y)
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text('Client Signature & Date', margin, y + 14)
  doc.text(`Authorized Signature (${settings.company_name || 'CHIMACY OF UNN'})`, margin + colWidth + 40, y + 14)

  const signatureDataUrl = await urlToDataUrl(settings.signature_url)
  if (signatureDataUrl) {
    try {
      doc.addImage(signatureDataUrl, imageFormatFromDataUrl(signatureDataUrl), margin + colWidth + 40, y - 45, 100, 40)
    } catch (e) {
      // ignore - signature is a nice-to-have, never blocks the document
    }
  }
}

export async function downloadQuotationPDF(quotation, settings) {
  try {
    const doc = await generateQuotationPDF(quotation, settings)
    doc.save(`Quotation-${quotation.quotationNumber || 'draft'}.pdf`)
  } catch (err) {
    alert('Could not generate the PDF. Please try again.')
  }
}

export async function downloadInvoicePDF(quotation, settings) {
  try {
    const doc = await generateInvoicePDF(quotation, settings)
    doc.save(`Invoice-${quotation.invoiceNumber || quotation.quotationNumber || 'draft'}.pdf`)
  } catch (err) {
    alert('Could not generate the PDF. Please try again.')
  }
}
